//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontDialogSample.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FontDialogSample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 的本地化字符串。
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 的本地化字符串。
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7 的本地化字符串。
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 的本地化字符串。
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9 的本地化字符串。
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All petite caps 的本地化字符串。
        /// </summary>
        internal static string AllPetiteCaps {
            get {
                return ResourceManager.GetString("AllPetiteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All small caps 的本地化字符串。
        /// </summary>
        internal static string AllSmallCaps {
            get {
                return ResourceManager.GetString("AllSmallCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Annotation alternates 的本地化字符串。
        /// </summary>
        internal static string AnnotationAlternates {
            get {
                return ResourceManager.GetString("AnnotationAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capitals 的本地化字符串。
        /// </summary>
        internal static string Capitals {
            get {
                return ResourceManager.GetString("Capitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capital spacing 的本地化字符串。
        /// </summary>
        internal static string CapitalSpacing {
            get {
                return ResourceManager.GetString("CapitalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Case sensitive forms 的本地化字符串。
        /// </summary>
        internal static string CaseSensitiveForms {
            get {
                return ResourceManager.GetString("CaseSensitiveForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contextual alternates 的本地化字符串。
        /// </summary>
        internal static string ContextualAlternates {
            get {
                return ResourceManager.GetString("ContextualAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ligatures, contextual 的本地化字符串。
        /// </summary>
        internal static string ContextualLigatures {
            get {
                return ResourceManager.GetString("ContextualLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swashes, contextual 的本地化字符串。
        /// </summary>
        internal static string ContextualSwashes {
            get {
                return ResourceManager.GetString("ContextualSwashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1, 2, 3, 4, 5, 6, 7, 8 ,9, 0 的本地化字符串。
        /// </summary>
        internal static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ligatures, discretionary 的本地化字符串。
        /// </summary>
        internal static string DiscretionaryLigatures {
            get {
                return ResourceManager.GetString("DiscretionaryLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 East Asian expert forms 的本地化字符串。
        /// </summary>
        internal static string EastAsianExpertForms {
            get {
                return ResourceManager.GetString("EastAsianExpertForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 East Asian language 的本地化字符串。
        /// </summary>
        internal static string EastAsianLanguage {
            get {
                return ResourceManager.GetString("EastAsianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 East Asian widths 的本地化字符串。
        /// </summary>
        internal static string EastAsianWidths {
            get {
                return ResourceManager.GetString("EastAsianWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fraction 的本地化字符串。
        /// </summary>
        internal static string Fraction {
            get {
                return ResourceManager.GetString("Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full 的本地化字符串。
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Half 的本地化字符串。
        /// </summary>
        internal static string Half {
            get {
                return ResourceManager.GetString("Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Historical forms 的本地化字符串。
        /// </summary>
        internal static string HistoricalForms {
            get {
                return ResourceManager.GetString("HistoricalForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ligatures, historical 的本地化字符串。
        /// </summary>
        internal static string HistoricalLigatures {
            get {
                return ResourceManager.GetString("HistoricalLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hojo Kanji 的本地化字符串。
        /// </summary>
        internal static string HojoKanji {
            get {
                return ResourceManager.GetString("HojoKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inferior 的本地化字符串。
        /// </summary>
        internal static string Inferior {
            get {
                return ResourceManager.GetString("Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JIS-04 的本地化字符串。
        /// </summary>
        internal static string Jis04 {
            get {
                return ResourceManager.GetString("Jis04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JIS-78 的本地化字符串。
        /// </summary>
        internal static string Jis78 {
            get {
                return ResourceManager.GetString("Jis78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JIS-83 的本地化字符串。
        /// </summary>
        internal static string Jis83 {
            get {
                return ResourceManager.GetString("Jis83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JIS-90 的本地化字符串。
        /// </summary>
        internal static string Jis90 {
            get {
                return ResourceManager.GetString("Jis90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kerning 的本地化字符串。
        /// </summary>
        internal static string Kerning {
            get {
                return ResourceManager.GetString("Kerning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lining 的本地化字符串。
        /// </summary>
        internal static string Lining {
            get {
                return ResourceManager.GetString("Lining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mathematical Greek 的本地化字符串。
        /// </summary>
        internal static string MathematicalGreek {
            get {
                return ResourceManager.GetString("MathematicalGreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NLC Kanji 的本地化字符串。
        /// </summary>
        internal static string NlcKanji {
            get {
                return ResourceManager.GetString("NlcKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeral alignment 的本地化字符串。
        /// </summary>
        internal static string NumeralAlignment {
            get {
                return ResourceManager.GetString("NumeralAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeral style 的本地化字符串。
        /// </summary>
        internal static string NumeralStyle {
            get {
                return ResourceManager.GetString("NumeralStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old style 的本地化字符串。
        /// </summary>
        internal static string OldStyle {
            get {
                return ResourceManager.GetString("OldStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/2 的本地化字符串。
        /// </summary>
        internal static string OneHalf {
            get {
                return ResourceManager.GetString("OneHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordinal 的本地化字符串。
        /// </summary>
        internal static string Ordinal {
            get {
                return ResourceManager.GetString("Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Petite caps 的本地化字符串。
        /// </summary>
        internal static string PetiteCaps {
            get {
                return ResourceManager.GetString("PetiteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proportional 的本地化字符串。
        /// </summary>
        internal static string Proportional {
            get {
                return ResourceManager.GetString("Proportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quarter 的本地化字符串。
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ruby 的本地化字符串。
        /// </summary>
        internal static string Ruby {
            get {
                return ResourceManager.GetString("Ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified 的本地化字符串。
        /// </summary>
        internal static string Simplified {
            get {
                return ResourceManager.GetString("Simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (simulated) 的本地化字符串。
        /// </summary>
        internal static string simulated {
            get {
                return ResourceManager.GetString("simulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slashed 的本地化字符串。
        /// </summary>
        internal static string Slashed {
            get {
                return ResourceManager.GetString("Slashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slashed zero 的本地化字符串。
        /// </summary>
        internal static string SlashedZero {
            get {
                return ResourceManager.GetString("SlashedZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small caps 的本地化字符串。
        /// </summary>
        internal static string SmallCaps {
            get {
                return ResourceManager.GetString("SmallCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stacked 的本地化字符串。
        /// </summary>
        internal static string Stacked {
            get {
                return ResourceManager.GetString("Stacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ligatures, standard 的本地化字符串。
        /// </summary>
        internal static string StandardLigatures {
            get {
                return ResourceManager.GetString("StandardLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swashes, standard 的本地化字符串。
        /// </summary>
        internal static string StandardSwashes {
            get {
                return ResourceManager.GetString("StandardSwashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic alternates 的本地化字符串。
        /// </summary>
        internal static string StylisticAlternates {
            get {
                return ResourceManager.GetString("StylisticAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set  1 的本地化字符串。
        /// </summary>
        internal static string StylisticSet1 {
            get {
                return ResourceManager.GetString("StylisticSet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 10 的本地化字符串。
        /// </summary>
        internal static string StylisticSet10 {
            get {
                return ResourceManager.GetString("StylisticSet10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 11 的本地化字符串。
        /// </summary>
        internal static string StylisticSet11 {
            get {
                return ResourceManager.GetString("StylisticSet11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 12 的本地化字符串。
        /// </summary>
        internal static string StylisticSet12 {
            get {
                return ResourceManager.GetString("StylisticSet12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 13 的本地化字符串。
        /// </summary>
        internal static string StylisticSet13 {
            get {
                return ResourceManager.GetString("StylisticSet13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 14 的本地化字符串。
        /// </summary>
        internal static string StylisticSet14 {
            get {
                return ResourceManager.GetString("StylisticSet14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 15 的本地化字符串。
        /// </summary>
        internal static string StylisticSet15 {
            get {
                return ResourceManager.GetString("StylisticSet15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 16 的本地化字符串。
        /// </summary>
        internal static string StylisticSet16 {
            get {
                return ResourceManager.GetString("StylisticSet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 17 的本地化字符串。
        /// </summary>
        internal static string StylisticSet17 {
            get {
                return ResourceManager.GetString("StylisticSet17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 18 的本地化字符串。
        /// </summary>
        internal static string StylisticSet18 {
            get {
                return ResourceManager.GetString("StylisticSet18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 19 的本地化字符串。
        /// </summary>
        internal static string StylisticSet19 {
            get {
                return ResourceManager.GetString("StylisticSet19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set  2 的本地化字符串。
        /// </summary>
        internal static string StylisticSet2 {
            get {
                return ResourceManager.GetString("StylisticSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set 20 的本地化字符串。
        /// </summary>
        internal static string StylisticSet20 {
            get {
                return ResourceManager.GetString("StylisticSet20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set  3 的本地化字符串。
        /// </summary>
        internal static string StylisticSet3 {
            get {
                return ResourceManager.GetString("StylisticSet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set  4 的本地化字符串。
        /// </summary>
        internal static string StylisticSet4 {
            get {
                return ResourceManager.GetString("StylisticSet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set  5 的本地化字符串。
        /// </summary>
        internal static string StylisticSet5 {
            get {
                return ResourceManager.GetString("StylisticSet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set  6 的本地化字符串。
        /// </summary>
        internal static string StylisticSet6 {
            get {
                return ResourceManager.GetString("StylisticSet6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set  7 的本地化字符串。
        /// </summary>
        internal static string StylisticSet7 {
            get {
                return ResourceManager.GetString("StylisticSet7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set  8 的本地化字符串。
        /// </summary>
        internal static string StylisticSet8 {
            get {
                return ResourceManager.GetString("StylisticSet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stylistic set  9 的本地化字符串。
        /// </summary>
        internal static string StylisticSet9 {
            get {
                return ResourceManager.GetString("StylisticSet9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscript 的本地化字符串。
        /// </summary>
        internal static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Superscript 的本地化字符串。
        /// </summary>
        internal static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tabular 的本地化字符串。
        /// </summary>
        internal static string Tabular {
            get {
                return ResourceManager.GetString("Tabular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Third 的本地化字符串。
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Titling 的本地化字符串。
        /// </summary>
        internal static string Titling {
            get {
                return ResourceManager.GetString("Titling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional 的本地化字符串。
        /// </summary>
        internal static string Traditional {
            get {
                return ResourceManager.GetString("Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional names 的本地化字符串。
        /// </summary>
        internal static string TraditionalNames {
            get {
                return ResourceManager.GetString("TraditionalNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unicase 的本地化字符串。
        /// </summary>
        internal static string Unicase {
            get {
                return ResourceManager.GetString("Unicase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variants 的本地化字符串。
        /// </summary>
        internal static string Variants {
            get {
                return ResourceManager.GetString("Variants", resourceCulture);
            }
        }
    }
}
